-- Migration: 0041_personnel_document_and_code_prefix.sql
-- Adds CPF/CNPJ (document) field to consultants, engineers, and installers.
-- Updates *_code CHECK constraints to enforce entity-specific prefix letters:
--   consultants  → code must start with 'C' or 'c'
--   engineers    → code must start with 'E' or 'e'
--   installers   → code must start with 'I' or 'i'
-- Codes are now auto-generated by the server at creation time; they are not
-- supplied by the client.
--
-- Safe to re-run (idempotent via IF NOT EXISTS / IF EXISTS guards).

BEGIN;

-- ─────────────────────────────────────────────────────────────────────────────
-- 1) consultants — add document column, unique index, update code constraint
-- ─────────────────────────────────────────────────────────────────────────────
ALTER TABLE public.consultants
  ADD COLUMN IF NOT EXISTS document TEXT;

-- One person (CPF/CNPJ) may only have one consultant record.
CREATE UNIQUE INDEX IF NOT EXISTS idx_consultants_document_unique
  ON public.consultants (document)
  WHERE document IS NOT NULL;

-- Update *_code format: must start with C/c followed by exactly 3 alphanumerics.
ALTER TABLE public.consultants
  DROP CONSTRAINT IF EXISTS consultants_code_format;
ALTER TABLE public.consultants
  ADD CONSTRAINT consultants_code_format
    CHECK (consultant_code ~ '^[Cc][A-Za-z0-9]{3}$');

-- ─────────────────────────────────────────────────────────────────────────────
-- 2) engineers — add document column, unique index, update code constraint
-- ─────────────────────────────────────────────────────────────────────────────
ALTER TABLE public.engineers
  ADD COLUMN IF NOT EXISTS document TEXT;

CREATE UNIQUE INDEX IF NOT EXISTS idx_engineers_document_unique
  ON public.engineers (document)
  WHERE document IS NOT NULL;

ALTER TABLE public.engineers
  DROP CONSTRAINT IF EXISTS engineers_code_format;
ALTER TABLE public.engineers
  ADD CONSTRAINT engineers_code_format
    CHECK (engineer_code ~ '^[Ee][A-Za-z0-9]{3}$');

-- ─────────────────────────────────────────────────────────────────────────────
-- 3) installers — add document column, unique index, update code constraint
-- ─────────────────────────────────────────────────────────────────────────────
ALTER TABLE public.installers
  ADD COLUMN IF NOT EXISTS document TEXT;

CREATE UNIQUE INDEX IF NOT EXISTS idx_installers_document_unique
  ON public.installers (document)
  WHERE document IS NOT NULL;

ALTER TABLE public.installers
  DROP CONSTRAINT IF EXISTS installers_code_format;
ALTER TABLE public.installers
  ADD CONSTRAINT installers_code_format
    CHECK (installer_code ~ '^[Ii][A-Za-z0-9]{3}$');

-- ─────────────────────────────────────────────────────────────────────────────
-- Comments
-- ─────────────────────────────────────────────────────────────────────────────
COMMENT ON COLUMN public.consultants.document IS 'CPF (11 digits) or CNPJ (14 digits) of the consultant. Unique per table. Permanently tied to the consultant_code assigned at creation.';
COMMENT ON COLUMN public.engineers.document   IS 'CPF (11 digits) or CNPJ (14 digits) of the engineer. Unique per table. Permanently tied to the engineer_code assigned at creation.';
COMMENT ON COLUMN public.installers.document  IS 'CPF (11 digits) or CNPJ (14 digits) of the installer. Unique per table. Permanently tied to the installer_code assigned at creation.';

COMMIT;
