import type { AfInputStore } from './useAfInputStore'

export const selectAfModo = (s: AfInputStore) => s.afModo
export const selectAfConsumoOverride = (s: AfInputStore) => s.afConsumoOverride
export const selectAfNumModulosOverride = (s: AfInputStore) => s.afNumModulosOverride
export const selectAfModuloWpOverride = (s: AfInputStore) => s.afModuloWpOverride
export const selectAfIrradiacaoOverride = (s: AfInputStore) => s.afIrradiacaoOverride
export const selectAfPROverride = (s: AfInputStore) => s.afPROverride
export const selectAfDiasOverride = (s: AfInputStore) => s.afDiasOverride
export const selectAfUfOverride = (s: AfInputStore) => s.afUfOverride
export const selectAfCustoKit = (s: AfInputStore) => s.afCustoKit
export const selectAfCustoKitManual = (s: AfInputStore) => s.afCustoKitManual
export const selectAfFrete = (s: AfInputStore) => s.afFrete
export const selectAfFreteManual = (s: AfInputStore) => s.afFreteManual
export const selectAfDescarregamento = (s: AfInputStore) => s.afDescarregamento
export const selectAfHotelPousada = (s: AfInputStore) => s.afHotelPousada
export const selectAfTransporteCombustivel = (s: AfInputStore) => s.afTransporteCombustivel
export const selectAfOutros = (s: AfInputStore) => s.afOutros
export const selectAfPlaca = (s: AfInputStore) => s.afPlaca
export const selectAfValorContrato = (s: AfInputStore) => s.afValorContrato
export const selectAfMensalidadeBase = (s: AfInputStore) => s.afMensalidadeBase
export const selectAfImpostosVenda = (s: AfInputStore) => s.afImpostosVenda
export const selectAfImpostosLeasing = (s: AfInputStore) => s.afImpostosLeasing
export const selectAfInadimplencia = (s: AfInputStore) => s.afInadimplencia
export const selectAfCustoOperacional = (s: AfInputStore) => s.afCustoOperacional
export const selectAfMesesProjecao = (s: AfInputStore) => s.afMesesProjecao
export const selectAfMargemLiquidaVenda = (s: AfInputStore) => s.afMargemLiquidaVenda
export const selectAfMargemLiquidaMinima = (s: AfInputStore) => s.afMargemLiquidaMinima
export const selectAfComissaoMinimaPercent = (s: AfInputStore) => s.afComissaoMinimaPercent
export const selectAfTaxaDesconto = (s: AfInputStore) => s.afTaxaDesconto
export const selectAfAutoMaterialCA = (s: AfInputStore) => s.afAutoMaterialCA
export const selectAfMaterialCAOverride = (s: AfInputStore) => s.afMaterialCAOverride
export const selectAfProjetoOverride = (s: AfInputStore) => s.afProjetoOverride
export const selectAfCreaOverride = (s: AfInputStore) => s.afCreaOverride

export const selectSetAfModo = (s: AfInputStore) => s.setAfModo
export const selectSetAfConsumoOverride = (s: AfInputStore) => s.setAfConsumoOverride
export const selectSetAfNumModulosOverride = (s: AfInputStore) => s.setAfNumModulosOverride
export const selectSetAfModuloWpOverride = (s: AfInputStore) => s.setAfModuloWpOverride
export const selectSetAfIrradiacaoOverride = (s: AfInputStore) => s.setAfIrradiacaoOverride
export const selectSetAfPROverride = (s: AfInputStore) => s.setAfPROverride
export const selectSetAfDiasOverride = (s: AfInputStore) => s.setAfDiasOverride
export const selectSetAfUfOverride = (s: AfInputStore) => s.setAfUfOverride
export const selectSetAfCustoKit = (s: AfInputStore) => s.setAfCustoKit
export const selectSetAfCustoKitManual = (s: AfInputStore) => s.setAfCustoKitManual
export const selectSetAfFrete = (s: AfInputStore) => s.setAfFrete
export const selectSetAfFreteManual = (s: AfInputStore) => s.setAfFreteManual
export const selectSetAfDescarregamento = (s: AfInputStore) => s.setAfDescarregamento
export const selectSetAfHotelPousada = (s: AfInputStore) => s.setAfHotelPousada
export const selectSetAfTransporteCombustivel = (s: AfInputStore) => s.setAfTransporteCombustivel
export const selectSetAfOutros = (s: AfInputStore) => s.setAfOutros
export const selectSetAfPlaca = (s: AfInputStore) => s.setAfPlaca
export const selectSetAfValorContrato = (s: AfInputStore) => s.setAfValorContrato
export const selectSetAfMensalidadeBase = (s: AfInputStore) => s.setAfMensalidadeBase
export const selectSetAfImpostosVenda = (s: AfInputStore) => s.setAfImpostosVenda
export const selectSetAfImpostosLeasing = (s: AfInputStore) => s.setAfImpostosLeasing
export const selectSetAfInadimplencia = (s: AfInputStore) => s.setAfInadimplencia
export const selectSetAfCustoOperacional = (s: AfInputStore) => s.setAfCustoOperacional
export const selectSetAfMesesProjecao = (s: AfInputStore) => s.setAfMesesProjecao
export const selectSetAfMargemLiquidaVenda = (s: AfInputStore) => s.setAfMargemLiquidaVenda
export const selectSetAfMargemLiquidaMinima = (s: AfInputStore) => s.setAfMargemLiquidaMinima
export const selectSetAfComissaoMinimaPercent = (s: AfInputStore) => s.setAfComissaoMinimaPercent
export const selectSetAfTaxaDesconto = (s: AfInputStore) => s.setAfTaxaDesconto
export const selectSetAfAutoMaterialCA = (s: AfInputStore) => s.setAfAutoMaterialCA
export const selectSetAfMaterialCAOverride = (s: AfInputStore) => s.setAfMaterialCAOverride
export const selectSetAfProjetoOverride = (s: AfInputStore) => s.setAfProjetoOverride
export const selectSetAfCreaOverride = (s: AfInputStore) => s.setAfCreaOverride
export const selectResetAfInputs = (s: AfInputStore) => s.resetAfInputs
