export const ANNEX_IDS = {
  DADOS_TECNICOS_USINA: 'DADOS_TECNICOS_USINA',
  PLANO_PAGAMENTO: 'PLANO_PAGAMENTO',
  MAPA_UC_ENDERECOS: 'MAPA_UC_ENDERECOS',
  CHECKLIST_PF: 'CHECKLIST_PF',
  CHECKLIST_PJ: 'CHECKLIST_PJ',
  CHECKLIST_CONDOMINIO: 'CHECKLIST_CONDOMINIO',
  AUT_PROPRIETARIO: 'AUT_PROPRIETARIO',
  ATA_CONDOMINIO: 'ATA_CONDOMINIO',
  ART_RRT: 'ART_RRT',
  TERMO_ESTRUTURAL: 'TERMO_ESTRUTURAL',
  OEM_GARANTIAS: 'OEM_GARANTIAS',
} as const

export type LeasingAnnexId = (typeof ANNEX_IDS)[keyof typeof ANNEX_IDS]
