// src/types/personnel.ts
// Type definitions for the Consultants, Engineers, and Installers entities.
// These are distinct from app users (app_user_profiles) — a person may be both.

export interface Consultant {
  id: number
  /** Auto-generated by the server at creation. Starts with 'C'. Permanently tied to document. */
  consultant_code: string
  full_name: string
  /** Optional display nickname. Falls back to full_name when null or empty. */
  apelido: string | null
  phone: string
  email: string
  /** CPF or CNPJ — stored as-entered. Unique per table. */
  document: string | null
  /** Array of Brazilian state abbreviations (UFs) */
  regions: string[]
  linked_user_id: string | null
  is_active: boolean
  created_at: string
  updated_at: string
  created_by_user_id: string | null
}

export interface Engineer {
  id: number
  /** Auto-generated by the server at creation. Starts with 'E'. Permanently tied to document. */
  engineer_code: string
  full_name: string
  phone: string
  email: string
  crea: string
  /** CPF or CNPJ — stored as-entered. Unique per table. */
  document: string | null
  linked_user_id: string | null
  is_active: boolean
  created_at: string
  updated_at: string
  created_by_user_id: string | null
}

export interface Installer {
  id: number
  /** Auto-generated by the server at creation. Starts with 'I'. Permanently tied to document. */
  installer_code: string
  full_name: string
  phone: string
  email: string
  /** CPF or CNPJ — stored as-entered. Unique per table. */
  document: string | null
  linked_user_id: string | null
  is_active: boolean
  created_at: string
  updated_at: string
  created_by_user_id: string | null
}

/** Code is NOT included — it is auto-generated server-side with prefix 'C'. */
export interface CreateConsultantRequest {
  full_name: string
  phone: string
  email: string
  document: string
  regions: string[]
  linked_user_id?: string | null
  /** Optional nickname. Defaults to first word of full_name server-side when omitted. */
  apelido?: string | null
}

export interface UpdateConsultantRequest {
  full_name: string
  phone: string
  email: string
  document?: string
  regions: string[]
  linked_user_id?: string | null
  /** Optional nickname. Pass empty string or null to clear. */
  apelido?: string | null
}

/** Code is NOT included — it is auto-generated server-side with prefix 'E'. */
export interface CreateEngineerRequest {
  full_name: string
  phone: string
  email: string
  crea: string
  document: string
  linked_user_id?: string | null
}

export interface UpdateEngineerRequest {
  full_name: string
  phone: string
  email: string
  crea: string
  document?: string
  linked_user_id?: string | null
}

/** Code is NOT included — it is auto-generated server-side with prefix 'I'. */
export interface CreateInstallerRequest {
  full_name: string
  phone: string
  email: string
  document: string
  linked_user_id?: string | null
}

export interface UpdateInstallerRequest {
  full_name: string
  phone: string
  email: string
  document?: string
  linked_user_id?: string | null
}

/** All Brazilian state abbreviations for region selection */
export const BRAZIL_UFS = [
  'AC', 'AL', 'AP', 'AM', 'BA', 'CE', 'DF', 'ES', 'GO',
  'MA', 'MT', 'MS', 'MG', 'PA', 'PB', 'PR', 'PE', 'PI',
  'RJ', 'RN', 'RS', 'RO', 'RR', 'SC', 'SP', 'SE', 'TO',
] as const

export type BrazilUF = (typeof BRAZIL_UFS)[number]

/** Generic 4-char alphanumeric regex (still used for general checks) */
export const PERSONNEL_CODE_REGEX = /^[A-Za-z0-9]{4}$/

/** Consultant code: starts with C/c + 3 alphanumerics (auto-generated by server) */
export const CONSULTANT_CODE_REGEX = /^[Cc][A-Za-z0-9]{3}$/
/** Engineer code: starts with E/e + 3 alphanumerics (auto-generated by server) */
export const ENGINEER_CODE_REGEX = /^[Ee][A-Za-z0-9]{3}$/
/** Installer code: starts with I/i + 3 alphanumerics (auto-generated by server) */
export const INSTALLER_CODE_REGEX = /^[Ii][A-Za-z0-9]{3}$/
