// src/components/dashboard/index.ts
export { DashboardFiltersPanel } from './DashboardFilters.js'
export { KpiCards } from './KpiCards.js'
export { ContractsChart } from './ContractsChart.js'
export { RevenueChart } from './RevenueChart.js'
export { ForecastPanel } from './ForecastPanel.js'
export { DrilldownTable } from './DrilldownTable.js'
export { ProjectsPanel } from './ProjectsPanel.js'
export { StatusBadge } from './StatusBadge.js'
export { OperationalKpiCards } from './OperationalKpiCards.js'
export { AlertsPanel } from './AlertsPanel.js'
export { InvoicesSection } from './InvoicesSection.js'
export { KitDeliverySection } from './KitDeliverySection.js'
export { InstallationSection } from './InstallationSection.js'
export { TechSupportSection } from './TechSupportSection.js'
export { NotificationPreferencesModal } from './NotificationPreferencesModal.js'
export { BlockTaskModal, RescheduleTaskModal } from './TaskActionModals.js'
